"""ID generation utilities for the catalyst observability layer.

Implements the 3-tier ID scheme finalized in Round 8/9 of the design dialectic:

- ``hypothesis_id`` — date-independent stable hash. Same investment hypothesis
  yields the same ``hypothesis_id`` across days, enabling multi-day join for
  attribution, opportunity-cost, and outcome aggregation.

- ``row_id`` — UUID per log row. Disambiguates physical writes; never collides.

- ``analysis_id`` — UUID per daily ``analyzer.py`` run. Groups all candidates
  generated by the same run for portfolio-level decisions.

- ``cash_decision_id`` — stable hash for cash-deployment-critic events. Joins
  the trigger row with subsequent ``follow_up_outcome`` rows in
  ``cash_deployment_log.jsonl``.

See plan §6.9 (candidate_packet schema) and §6.14 (catalyst_outcome_log).
"""

from __future__ import annotations

import hashlib
import uuid

__all__ = [
    "compute_hypothesis_id",
    "compute_source_event_id",
    "new_row_id",
    "new_analysis_id",
    "new_cash_decision_id",
]

# Truncation length for stable hashes. 16 hex chars = 64 bits of entropy,
# more than enough to avoid collisions across a personal-scale portfolio
# while keeping log rows compact and human-readable.
_HASH_TRUNC = 16


def compute_hypothesis_id(
    ticker: str,
    action_type: str,
    hypothesis_type: str,
    horizon_days: int,
    source_event_id: str,
) -> str:
    """Compute a date-independent stable hash for a hypothesis.

    The same logical investment hypothesis — "buy NVDA on earnings_revision
    over 10 days driven by source event X" — yields the same hash every day
    it is regenerated, which is the prerequisite for multi-day tracking of
    opportunity cost and agent attribution (Round 8 #1 / Round 9 #1).

    ``analysis_date`` is deliberately NOT in the hash; same-day uniqueness
    comes from ``row_id`` instead.

    Parameters
    ----------
    ticker : str
        Ticker symbol (e.g. ``"NVDA"``, ``"9984.T"``).
    action_type : str
        One of ``buy / margin_buy / short_sell / sell / trim / hold``.
        ``no_action`` is intentionally excluded (Round 11 #4): it is a
        portfolio-level decision state, not a candidate action.
    hypothesis_type : str
        Playbook label such as ``ipo_proxy`` / ``bull_pullback`` /
        ``earnings_revision_pullback``.
    horizon_days : int
        Intended holding horizon in calendar days.
    source_event_id : str
        Stable identifier for the originating event (news URL hash, scenario
        key, earnings calendar slot, etc.). Required for join stability;
        callers must supply a non-empty value.

    Returns
    -------
    str
        16-char hex hash. Format ``"sha256:<16hex>"`` is intentionally
        avoided here so the value can be used as a JSON key directly.

    Raises
    ------
    ValueError
        If ``source_event_id`` is empty. Empty event IDs would collapse
        unrelated hypotheses into one and break attribution.
    """
    if not source_event_id:
        raise ValueError(
            "source_event_id must be non-empty; empty IDs cause hypothesis "
            "collision and break attribution (see plan R19)."
        )
    payload = f"{ticker}|{action_type}|{hypothesis_type}|{horizon_days}|{source_event_id}"
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:_HASH_TRUNC]


def compute_source_event_id(
    source: str,
    *,
    native_doc_id: str | None = None,
    source_url: str | None = None,
) -> str:
    """Stable, idempotent identifier for a public disclosure / news event.

    Used by the Phase-0 public-disclosure feature pipeline as the dedup and
    join key for ``data/disclosure_features.jsonl`` and as the
    ``source_event_id`` fed into :func:`compute_hypothesis_id`.

    A *native* document id is strongly preferred — EDGAR accession number,
    EDINET ``docID``, TDnet disclosure id — because those are issued by the
    source of record and survive URL changes and corrected re-filings, which a
    URL hash does not. The URL hash is a fallback for items that carry no
    native id (most news headlines).

    The value is namespaced by ``source`` so the same raw doc id in two systems
    cannot collide, e.g. ``"edgar:0000320193-24-000123"`` or
    ``"news:url:ab12cd34ef567890"``.

    Parameters
    ----------
    source : str
        Originating system, e.g. ``"edgar"`` / ``"edinet"`` / ``"tdnet"`` /
        ``"news"``. Lower-cased and stripped for stability.
    native_doc_id : str, optional
        Source-of-record document id. When present it anchors the event id.
    source_url : str, optional
        Canonical URL. Hashed (16-hex sha256) only when ``native_doc_id`` is
        absent.

    Returns
    -------
    str
        ``"<source>:<native_doc_id>"`` or ``"<source>:url:<16hex>"``.

    Raises
    ------
    ValueError
        If ``source`` is empty, or if neither ``native_doc_id`` nor
        ``source_url`` is provided — an event with no stable anchor cannot be
        deduplicated and must be rejected at ingestion rather than silently
        producing colliding ids.
    """
    src = (source or "").strip().lower()
    if not src:
        raise ValueError("source must be non-empty")
    native = (native_doc_id or "").strip()
    if native:
        return f"{src}:{native}"
    url = (source_url or "").strip()
    if url:
        digest = hashlib.sha256(url.encode("utf-8")).hexdigest()[:_HASH_TRUNC]
        return f"{src}:url:{digest}"
    raise ValueError(
        "compute_source_event_id requires native_doc_id or source_url; an "
        "event with no stable anchor cannot be deduplicated."
    )


def new_row_id() -> str:
    """Return a fresh UUID4 string for a log row."""
    return str(uuid.uuid4())


def new_analysis_id() -> str:
    """Return a fresh UUID4 string for an analyzer.py run."""
    return str(uuid.uuid4())


def new_cash_decision_id(
    analysis_date: str,
    risk_mode: str,
    cash_ratio: float,
) -> str:
    """Compute a stable hash for a cash-deployment-critic decision.

    Used to join the ``critic_triggered`` event row with subsequent
    ``follow_up_outcome`` rows in ``cash_deployment_log.jsonl``
    (Round 11 #2).

    Parameters
    ----------
    analysis_date : str
        ISO date (``YYYY-MM-DD``). The decision is unique per day.
    risk_mode : str
        ``aggressive`` / ``defensive`` / ``neutral``.
    cash_ratio : float
        Cash ratio at the time of the decision, rounded to 4 decimals so
        trivial drift between trigger and follow-up does not desync the ID.

    Returns
    -------
    str
        16-char hex hash.
    """
    payload = f"{analysis_date}|{risk_mode}|{cash_ratio:.4f}"
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:_HASH_TRUNC]
